### ISSUE TITLE
Why 'Checking for existing people...' when importing a Batch.csv

### ISSUE THREAD

**Issue by ElimAdmin** [KingdomFirst/Bulldozer#6]
Just wondering if this is needed, or if the wording of the check is misleading.
The batch file has only one line, and it takes some time Checking for existing people...

**Comment by treyhendon** [comment]
That is one part of what is going on behind the scenes at that point in time.  I can add additional feedback for the other data elements Bulldozer loading.  Or I might simplify that wording and leave a single line feedback.

Even though you only have the batch file, at that time, the application doesn't know what files are loaded.  It's pre-loading all previously imported data (people, transactions, families, etc) so that when Bulldozer does start processing the CSV files, it's ready to go.
